[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_solana = "AQJhSNZ9KCgTdmp6d5TL8uXuZSJRuwQe1noB7Xv3gBKR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
